### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by sandeep-v1404** [Worktrolly/worktrolly#115]
**Title**: 404 Error in Website
---

**Description:**

When we open WorkTrolly and refresh the website it throws 404 error and default firebase-error page.

**Steps to reproduce the behavior:**

1. Go to any page in WorkTrolly
2. Click on Refresh button
3. You will notice this error.

**Expected behavior:**

It should load the same page when refreshed.

**Screenshots:**
![image](https://user-images.githubusercontent.com/57038543/106563117-52bff400-6551-11eb-9033-466a24184cd6.png)

**Additional context:**

**Fix**: Go to the below link to get fix for this error.
https://stackoverflow.com/questions/34415725/when-i-refresh-my-website-i-get-a-404-this-is-with-angular2-and-firebase

**Comment by viv9k** [comment]
Fixed in pr #116
